import { defineConfig } from "@adobe/aio-commerce-lib-app/config";

const field = (name: string, source?: string) =>
  source ? { name, source } : { name };

const COPY_NUMBER = /^[0-9]+$/;
const APP_ID = /^[a-z0-9-]+$/;

/**
 * Which copy of this app a deploy builds, and what it calls itself to Commerce.
 *
 * Commerce knows an App Management app by its `metadata.id`, and the library names the
 * app's webhooks and events from it, so a second copy on the same Commerce store needs an
 * id of its own. Demo Builder decides that id — it is the only side that knows the other
 * copies — and sends it as DEMO_BUILDER_APP_ID, the name the SC gave this ERP
 * ("Contoso ERP" -> `contoso-erp`), so Commerce's Webhooks List says which ERP a hook
 * belongs to. Without it, DEMO_BUILDER_COPY_NUMBER alone still names the copy
 * (`erp-integration-2`), which is what a copy the SC never named gets.
 *
 * The first copy is deployed with neither and keeps the id it was installed with, which
 * Commerce refuses to change on an upgrade. Read at build time: the running actions read
 * the generated manifest.
 */
function copyIdentity(): { appId: string; menuId: string } {
  const copy = process.env.DEMO_BUILDER_COPY_NUMBER?.trim();
  const given = process.env.DEMO_BUILDER_APP_ID?.trim();
  if (!copy && !given) {
    return { appId: "commerce-erp-integration", menuId: "erp_integration" };
  }
  if (given) {
    if (!APP_ID.test(given)) {
      throw new Error(
        `DEMO_BUILDER_APP_ID must be lower-case letters, digits and hyphens, not "${given}".`,
      );
    }
    return { appId: given, menuId: given.replace(/-/g, "_") };
  }
  if (!COPY_NUMBER.test(copy as string)) {
    throw new Error(
      `DEMO_BUILDER_COPY_NUMBER must be a number, not "${copy}".`,
    );
  }
  // Not `commerce-erp-integration-2`: the library counts a webhook as an app's when its
  // name starts with the app's id, so that id would make the first copy's upgrade and
  // removal treat the second copy's webhooks as its own and delete them.
  return {
    appId: `erp-integration-${copy}`,
    menuId: `erp_integration_${copy}`,
  };
}

const { appId, menuId } = copyIdentity();
/** What the Admin menu and the app are called: the ERP's name, so two ERPs read apart. */
const erpName = process.env.ERP_DISPLAY_NAME?.trim() || "ERP integration";

/**
 * What this app declares to Commerce. Regenerated into
 * src/commerce-extensibility-1/.generated by the pre-app-build hook.
 *
 * Orders reach the ERP from Commerce's order save event, as Adobe's integration starter kit
 * sends them: after the order is saved, with the ERP number written back and I/O Events
 * delivering again while the ERP is offline (src/lib/order-sync.js).
 *
 * Two webhooks carry what must answer while the shopper waits: contract prices and the
 * discount ceiling at cart time. Both are `required: false` with a one-second soft timeout
 * on purpose: when the ERP is offline Commerce keeps its own prices.
 *
 * The ERP → Commerce direction is the kit's back-office eventing: the ERP posts its events
 * to the ingestion webhook, they are published to the `erp` provider, and the handler
 * actions below apply them to Commerce.
 */
export default defineConfig({
  adminUi: {
    menu: {
      description:
        "Health of the ERP integration, sync log, reset and controls",
      id: menuId,
      label: erpName,
      pageTitle: erpName,
      parentMenu: "system",
    },
  },
  // The merchant's settings, kept per scope (default, website, store, store view) by
  // @adobe/aio-commerce-lib-config and edited on the integration's Admin page. Read
  // through src/lib/settings.js, which answers these defaults when a read fails.
  businessConfig: {
    schema: [
      {
        default: true,
        description:
          "Orders placed on this website are created in the ERP, and the ERP's order number is written back.",
        label: "Send orders to the ERP",
        name: "orders_send",
        type: "boolean",
      },
      {
        default: true,
        description:
          "An order placed while the ERP is offline is sent when the ERP is back (retried for up to a day). When off, such an order is not sent.",
        label: "Hold orders while the ERP is offline",
        name: "orders_hold_offline",
        type: "boolean",
      },
      {
        default: true,
        description:
          "When the ERP confirms an order, its Commerce status becomes Processing.",
        label: "Mark orders Processing when the ERP confirms them",
        name: "orders_status_on_confirm",
        type: "boolean",
      },
      {
        default: true,
        description:
          "Cart prices come from the ERP's contract prices for the buyer's company.",
        label: "Use ERP contract prices in the cart",
        name: "pricing_contract_prices",
        type: "boolean",
      },
      {
        default: true,
        description:
          "A cart discount larger than the ERP allows for the buyer is reduced to the ERP's limit.",
        label: "Apply the ERP's maximum discount",
        name: "pricing_discount_ceiling",
        type: "boolean",
      },
    ],
  },
  eventing: {
    commerce: [
      {
        events: [
          {
            description:
              "Fires after a product is created or updated in Commerce, used to keep the ERP materials in step between resets",
            fields: [
              field("id"),
              field("sku"),
              field("name"),
              field("price"),
              field("type_id"),
              field("created_at"),
              field("updated_at"),
            ],
            label: "Product Created or Updated",
            name: "observer.catalog_product_save_commit_after",
            runtimeActions: [
              "product-commerce/created",
              "product-commerce/updated",
            ],
          },
          {
            description:
              "Fires after a product is deleted in Commerce, so the ERP copy goes too instead of lingering until the next reset",
            fields: [field("id"), field("sku")],
            label: "Product Deleted",
            name: "observer.catalog_product_delete_commit_after",
            runtimeActions: ["product-commerce/deleted"],
          },
          {
            description:
              "Fires after an order is saved in Commerce, used to create each new order in the ERP and write back the ERP order number",
            fields: [
              field("increment_id"),
              field("store_id"),
              field("ext_order_id"),
              field("customer_email"),
              field("customer_group_id"),
              field("customer_id"),
              field("base_grand_total"),
              field("base_currency_code"),
              field("created_at"),
              field("updated_at"),
              field("_isNew"),
              field("state"),
              field("status"),
              field("items[].item_id"),
              field("items[].sku"),
              field("items[].qty_ordered"),
              field("items[].base_price"),
              field("items[].parent_item_id"),
            ],
            label: "Order Saved",
            name: "observer.sales_order_save_commit_after",
            runtimeActions: ["order-commerce/created", "order-commerce/changed"],
          },
          {
            description:
              "Fires after a shipment is saved in Commerce, so a shipment made in Commerce Admin is recorded on the ERP order",
            fields: [
              field("entity_id"),
              field("order_id"),
              field("increment_id"),
              field("items[].order_item_id"),
              field("items[].qty"),
              field("items[].sku"),
              field("extension_attributes.source_code"),
            ],
            label: "Shipment Saved",
            name: "observer.sales_order_shipment_save_after",
            runtimeActions: ["order-commerce/shipped"],
          },
          {
            description:
              "Fires after an invoice is saved in Commerce, so an invoice made in Commerce Admin invoices the ERP order",
            fields: [
              field("entity_id"),
              field("order_id"),
              field("increment_id"),
              field("state"),
            ],
            label: "Invoice Saved",
            name: "observer.sales_order_invoice_save_after",
            runtimeActions: ["order-commerce/invoiced"],
          },
          {
            description:
              "Fires after a stock item is saved in Commerce, used to keep the ERP stock in step with the store",
            fields: [
              field("item_id"),
              field("product_id"),
              field("qty"),
              field("is_in_stock"),
            ],
            label: "Stock Item Updated",
            name: "observer.cataloginventory_stock_item_save_commit_after",
            runtimeActions: ["stock-commerce/updated"],
          },
        ],
        provider: {
          description: "Commerce events the ERP integration listens to",
          key: "commerce",
          label: "Commerce Provider",
        },
      },
    ],
    external: [
      {
        events: [
          {
            description: "The ERP changed a product price or name",
            label: "ERP Product Updated",
            name: "be-observer.catalog_product_update",
            runtimeActions: ["product-backoffice/updated"],
          },
          {
            description: "The ERP changed stock levels",
            label: "ERP Stock Updated",
            name: "be-observer.catalog_stock_update",
            runtimeActions: ["stock-backoffice/updated"],
          },
          {
            description: "The ERP confirmed a sales order",
            label: "ERP Order Status Updated",
            name: "be-observer.sales_order_status_update",
            runtimeActions: ["order-backoffice/updated"],
          },
          {
            description: "The ERP shipped a sales order",
            label: "ERP Order Shipment Created",
            name: "be-observer.sales_order_shipment_create",
            runtimeActions: ["order-backoffice/shipment-created"],
          },
          {
            description: "The ERP invoiced a sales order",
            label: "ERP Order Invoice Created",
            name: "be-observer.sales_order_invoice_create",
            runtimeActions: ["order-backoffice/invoice-created"],
          },
          {
            description: "The ERP cancelled a sales order",
            label: "ERP Order Cancelled",
            name: "be-observer.sales_order_cancel",
            runtimeActions: ["order-backoffice/cancelled"],
          },
          {
            description:
              "The ERP put a sales order on credit hold, or released it",
            label: "ERP Order Credit Hold",
            name: "be-observer.sales_order_hold",
            runtimeActions: ["order-backoffice/hold"],
          },
          {
            description: "The ERP changed an account credit limit",
            label: "ERP Company Credit Updated",
            name: "be-observer.company_credit_update",
            runtimeActions: ["company-backoffice/credit-updated"],
          },
          {
            description: "The ERP blocked or unblocked an account",
            label: "ERP Company Status Updated",
            name: "be-observer.company_status_update",
            runtimeActions: ["company-backoffice/status-updated"],
          },
        ],
        provider: {
          description:
            "The ERP, the back-office system that publishes these events",
          key: "erp",
          label: "ERP Provider",
        },
      },
    ],
  },
  metadata: {
    description:
      "Adobe Commerce integration to a demo ERP: orders to the ERP with the ERP number written back, contract pricing at cart time, and the ERP events (prices, stock, credit limits, order statuses) applied to Commerce.",
    displayName: erpName,
    id: appId,
    // Upgrades an installed app when this version changes (lib-app 2.x): webhooks, events and
    // the Admin UI registration are brought to this config after each deploy. Bump the
    // version with every change to what this file registers, or the change never reaches
    // Commerce. "auto" runs the plan; the library marks it experimental.
    upgradeMode: "auto",
    version: "0.5.0",
  },
  webhooks: [
    {
      category: "modification",
      description:
        "Replaces each cart line price with the ERP contract price for the buyer business partner",
      label: "ERP contract prices into cart totals",
      requireAdobeAuth: true,
      runtimeAction: "webhook/item-prices",
      webhook: {
        batch_name: "erp_totals_collector_item_prices",
        fallback_error_message:
          "ERP pricing is unavailable; Commerce kept its own prices for this cart.",
        hook_name: "erp_contract_price",
        method: "POST",
        required: false,
        soft_timeout: 1000,
        timeout: 5000,
        webhook_method:
          "plugin.out_of_process_totals_collector.api.get_total_modifications.item_prices",
        webhook_type: "after",
      },
    },
    {
      category: "modification",
      description:
        "Caps the combined discount on each cart line at the ERP maximum-discount ceiling for the buyer business partner",
      label: "ERP discount ceiling",
      requireAdobeAuth: true,
      runtimeAction: "webhook/discounts",
      webhook: {
        batch_name: "erp_totals_collector",
        fallback_error_message:
          "ERP discounts are unavailable; Commerce kept its own totals for this cart.",
        hook_name: "erp_discount_ceiling",
        method: "POST",
        required: false,
        soft_timeout: 1000,
        timeout: 5000,
        webhook_method:
          "plugin.out_of_process_totals_collector.api.get_total_modifications.execute",
        webhook_type: "after",
      },
    },
  ],
});
